// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllNode():Promise<string>;

export function GetBestNode():Promise<string>;

export function GetInfo():Promise<string>;

export function GetSpeed():Promise<string>;

export function InitNode():Promise<string>;

export function PingSelectedNode(arg1:number):Promise<string>;

export function StartTest(arg1:Array<number>,arg2:number,arg3:number):Promise<void>;
