// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllNode() {
  return window['go']['service']['App']['GetAllNode']();
}

export function GetBestNode() {
  return window['go']['service']['App']['GetBestNode']();
}

export function GetInfo() {
  return window['go']['service']['App']['GetInfo']();
}

export function GetSpeed() {
  return window['go']['service']['App']['GetSpeed']();
}

export function InitNode() {
  return window['go']['service']['App']['InitNode']();
}

export function PingSelectedNode(arg1) {
  return window['go']['service']['App']['PingSelectedNode'](arg1);
}

export function StartTest(arg1, arg2, arg3) {
  return window['go']['service']['App']['StartTest'](arg1, arg2, arg3);
}
