name: Build and Package Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            goos: linux
            suffix: linux-amd64
          - os: ubuntu-latest
            arch: arm64
            goos: linux
            suffix: linux-arm64
          - os: macos-latest
            arch: x64
            goos: darwin
            suffix: macos-amd64
          - os: macos-latest
            arch: arm64
            goos: darwin
            suffix: macos-arm64
          - os: windows-latest
            arch: x64
            goos: windows
            suffix: windows-amd64
          - os: windows-latest
            arch: ARM64
            goos: windows
            suffix: windows-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Setup PATH for Wails
        run: echo "$$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Make Clean & Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
        run: |
          make clean
          make

      - name: Upload Artifact (v4)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suffix }}
          path: build/*
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifact directories
        run: |
          mkdir -p release
          find artifacts -type f -exec cp {} release/ \;

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
